### ISSUE TITLE
Bad name in package.json

### ISSUE THREAD

**Issue by mattpetersen** [Bunkerbewohner/tidal-music-linux#10]
In package.json the name on the second line, “Tidal music - Linux”, creates an install error. Changing it to "tidal-music-linux” solved the error for me.

I'm on Arch linux with npm 4.6.1.

`npm version`
{ npm: '4.6.1',
  ares: '1.12.0',
  cldr: '31.0.1',
  http_parser: '2.7.1',
  icu: '59.1',
  modules: '57',
  node: '8.1.2',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }

**Comment by Bunkerbewohner** [comment]
Considered fixed thanks to https://github.com/Bunkerbewohner/tidal-music-linux/pull/11
