### ISSUE TITLE
Not packaged?

### ISSUE THREAD

**Issue by joshdaws0n** [Bunkerbewohner/tidal-music-linux#16]
I've got this running using npm but I'm completely unaware of how to package and properly install this as an application so I can launch it from the elementary wingpanel and keep it in the dock.

Can you help?

**Comment by ndrewtl** [comment]
I submitted a PR on this, #29. If it gets merged, you should be able to build and install in ~3 shell commands. Also it's been a year and a half so I hope this still helps!

**Comment by ndrewtl** [comment]
Added instructions. This should be possible if you follow the instructions in the `README`. Closing now, add another comment if you still have issues!
