### ISSUE TITLE
Unable to install on Debian Buster (testing)

### ISSUE THREAD

**Issue by OneAdder** [Bunkerbewohner/tidal-music-linux#21]
I cloned the repo and installed npm. Then I try `sudo npm install`
I get:
```
> abstract-socket@2.0.0 install /home/misha/tidal-music-linux/node_modules/abstract-socket
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/misha/tidal-music-linux/node_modules/abstract-socket/build'
gyp ERR! System Linux 4.18.0-1-amd64
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/misha/tidal-music-linux/node_modules/abstract-socket
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 (node_modules/abstract-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
At first I thought it was due to the fact that it was inside a directory with cyrillic name. But no. From latin directory it returns the same.

NPM version is 5.8.0

"misha" has rights for both writing and reading /home/misha

**Comment by OneAdder** [comment]
I solved this problem. I have no idea how it works (I don't use NodeJS myself). What I tried was to install electron and tidal-music-linux via npm using sudo. It would fail. I deleted both.
Then I did `sudo su -l` and install them in `/root`.Then copied to my home. Now it works.
It shouldn't solve the problem. But somehow it did

**Comment by ImSugarFree** [comment]
`sudo npm install -g electron --unsafe-perm=true`
helps.
