### ISSUE TITLE
Black Screen on login

### ISSUE THREAD

**Issue by Hokseed** [Bunkerbewohner/tidal-music-linux#22]
Hi,

When i try to login to my account, i enter my username (and complete the captchat) and before entering my password, i have a black screen on the app.

Archlinux - i3 | France.

**Comment by alberdingk-thijm** [comment]
I'm having the same issue using Antergos with Openbox and electron v2.0.11

Possibly an [electron](https://github.com/electron/electron/) related bug, according to Sarithis [on the AUR](https://aur.archlinux.org/packages/tidal-music-linux-git/).

**Comment by bliz937** [comment]
I changed the dependencies in **package.json** to
```
"dependencies": {
    "dbus-native": "^0.2.5",
    "electron": "^3.0.4"
  }
```

and re-ran ```npm install && npm start``` 

Electron is new to me, but this got me past the login screen.

**Comment by alberdingk-thijm** [comment]
@bliz937's solution works for me.
