### ISSUE TITLE
A few changes and roadmap

### ISSUE THREAD

**Issue by ndrewtl** [Bunkerbewohner/tidal-music-linux#30]
## Ideas

Hi @Bunkerbewohner et. al, and thanks so much for adding me as a contributor. I really like this project. I had a few ideas to implement to modernize and maintain this project. I'd really like to implement them, but I wanted to get your opinion and see what you think before I did anything.

Here are my ideas, by order of least to most disruptive change:

### Switch to yarn

Yarn is a modern build tool that provides the same features as `npm` but is simpler and more reliable. It's [recommended](https://aur.archlinux.org/packages/tidal-music-linux-git/) by electron-builder, and in my opinion much easier to use.

In terms of changes, this would mean simply [committing](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) a `yarn.lock` file, and changing threeish lines in the `README` to recommend using yarn for building and scripting.

### Move development to a development branch

I'm not very comfortable with regularly committing to the master branch, which is used as the base for a direct download in [at least one](https://aur.archlinux.org/packages/tidal-music-linux-git/) location.

A new development branch would allow us greater freedom and also create a simple workflow for building releases and distributing binaries. With every merge commit from the development branch into `master`, we can make a release and also attach binaries. All in all, this would allow for more adventurous code in the unstable branch, and create a stable development cycle.

### Clean up / modernize code

This would mean using more modern Javascript features, such as using `const` when declaring values that don't change. I'd also like to comment the code, and maybe pretty it up a bit by aligning the sequential assignments, for instance. All in all, this should be pretty minor.

### Compile-to-javascript

The last idea is the most drastic, and is more of a discussion-starter than a plan I currently intend to carry out. There are a bunch of compile-to-Javascript languages out there that could help development. Typescript is in vogue nowadays, while I'm aesthetically inclined toward Coffeescript. This is likely overkill for a project that comprises only a single file, but (admittedly more as a personal hobby than anything else) it might be fun to write up this code in another language.

I've written this on an issue, so feel free to close this / move the discussion elsewhere if you see fit. Thanks again!

**Comment by Bunkerbewohner** [comment]
Hey ndrewtl! Well thank you for contributing! :D

**Switch to Yarn**

Sure! I don't see anything that speaks against it! 

**Move development to a development branch**

Definitely! While I was basically working on this alone there was no need. But now it could definitely be useful! How should we call it, just "develop"? Maybe if I find the time we could even set up some CI workflow.

**Clean up / modernize code**

Knock yourself out! Feel free to modernize as long as it doesn't break anything!

**Compile-to-javascript**

As you said this is probably overkill for a single file. Also sticking with plain JavaScript makes it easier for others to contribute, even if they don't know languages like CoffeeScript or TypeScript.

**Comment by ndrewtl** [comment]
Thanks for the feedback! I'll create the new branch, and get started on changes.
