### ISSUE TITLE
High-fidelity playback is only available with Google Chrome

### ISSUE THREAD

**Issue by julien-gargot** [Bunkerbewohner/tidal-music-linux#7]
Hello,
As we know, HIFI playback is only supported in Google Chrome.
Would there be a way to allow it in an Electrons package? By loading additional modules for Flac?

**Comment by Bunkerbewohner** [comment]
Unfortunately not. [Tidal HiFi requires a NaCl plugin to work](https://support.tidal.com/hc/en-us/articles/202654692-HiFi-Option-is-Greyed-Out-Not-Selectable-), which [electron does not support](https://github.com/electron/electron/issues/835).

Native FLAC support is coming up in Chromium, though Tidal would also have to actively make use of that. So Tidal HiFi remains limited to Chrome for now. :-/
